library(ISLR)
set.seed(2019)
summary(OJ)
train=sample(seq_len(nrow(OJ)),800)
train.OJ=OJ[train,]
test.OJ=OJ[-train,]             
library(e1071)
svm.OJ<-svm(Purchase~.,data=train.OJ,kernel="linear",cost=0.01)
summary(svm.OJ)
train.OJ.pred<-predict(svm.OJ,train.OJ)
table(predict=train.OJ.pred,truth=train.OJ$Purchase)
test.OJ.pred<-predict(svm.OJ,test.OJ)
table(predict=test.OJ.pred,truth=test.OJ$Purchase)
?tune
tune.OJ<-tune(svm,Purchase~.,data=train.OJ,kernel="linear",ranges=list(cost=
seq(from=0.01,to=10,length=100)))
summary(tune.OJ)
best.OJ<-tune.OJ$best.model
train.OJ.best.pred<-predict(best.OJ,train.OJ)
table(predict=train.OJ.best.pred,truth=train.OJ$Purchase)
test.OJ.best.pred<-predict(best.OJ,test.OJ)
table(predict=test.OJ.best.pred,truth=test.OJ$Purchase)
##########radial
svm.OJ<-svm(Purchase~.,data=train.OJ,kernel="radial",cost=0.01)
summary(svm.OJ)
train.OJ.pred<-predict(svm.OJ,train.OJ)
table(predict=train.OJ.pred,truth=train.OJ$Purchase)
test.OJ.pred<-predict(svm.OJ,test.OJ)
table(predict=test.OJ.pred,truth=test.OJ$Purchase)
?tune
tune.OJ<-tune(svm,Purchase~.,data=train.OJ,kernel="radial",ranges=list(cost=
  seq(from=0.01,to=10,length=100)))
summary(tune.OJ)
best.OJ<-tune.OJ$best.model
train.OJ.best.pred<-predict(best.OJ,train.OJ)
table(predict=train.OJ.best.pred,truth=train.OJ$Purchase)
test.OJ.best.pred<-predict(best.OJ,test.OJ)
table(predict=test.OJ.best.pred,truth=test.OJ$Purchase)
###########degree 2 polynomial
svm.OJ<-svm(Purchase~.,data=train.OJ,kernel="polynomial",degree=2,cost=0.01)
summary(svm.OJ)
train.OJ.pred<-predict(svm.OJ,train.OJ)
table(predict=train.OJ.pred,truth=train.OJ$Purchase)
test.OJ.pred<-predict(svm.OJ,test.OJ)
table(predict=test.OJ.pred,truth=test.OJ$Purchase)
?tune
tune.OJ<-tune(svm,Purchase~.,data=train.OJ,kernel="polynomial",degree=2,ranges=list(cost=
                                                                         seq(from=0.01,to=10,length=100)))
summary(tune.OJ)
best.OJ<-tune.OJ$best.model
train.OJ.best.pred<-predict(best.OJ,train.OJ)
table(predict=train.OJ.best.pred,truth=train.OJ$Purchase)
test.OJ.best.pred<-predict(best.OJ,test.OJ)
table(predict=test.OJ.best.pred,truth=test.OJ$Purchase)
