load("/Users/ansonliu/Downloads/body.RData")
install.packages("pls")
library(pls)
par(mfrow=c(1,2))
plot(Y$Gender,Y$Height);plot(Y$Gender,Y$Weight)
set.seed(2019)
train=sample(seq_len(nrow(X)),size=307)
train.X=X[train,]
train.Y=Y[train,]
test.X=X[-train,]
test.Y=Y[-train,]
?pcr
pcr.fit<-pcr(train.Y$Weight~.,data=train.X,scale=TRUE,validation="CV")
?plsr
plsr.fit<-plsr(train.Y$Weight~.,data=train.X,scale=TRUE,validation="CV")
summary(pcr.fit)
summary(plsr.fit)
?validationplot
validationplot(pcr.fit,val.type="R2",main="PCR")
validationplot(plsr.fit,val.type="R2",main="PLSR")
pcr.pred=predict(pcr.fit,newdata=test.X,ncomp=5)
plsr.pred=predict(plsr.fit,newdata=test.X,ncomp=5)
mean((pcr.pred-test.Y$Weight)^2)
mean((plsr.pred-test.Y$Weight)^2)
